### PR TITLE
Add extra annotations to ingress

### PR DESCRIPTION
**Pull request by QuentinBisson**

### CODE REVIEW

**Comment by webwurst** [comment]
Does it work like that? Do you want the annotations written as strings including `- ` as prefix? Or should they be key-value pairs? I am lacking experience here, but examples in upstream documentation look different for [lists](https://helm.sh/docs/chart_template_guide/control_structures/) and [key-value pairs](https://helm.sh/docs/chart_template_guide/variables/).

**Comment by QuentinBisson** [comment]
Yes it works  as I tested it with the following value:
  extraAnnotations:
  - "giantswarm.io/external-dns: ecom-pucis-net"

I took this way of doing it from the nginx IC app https://github.com/giantswarm/nginx-ingress-controller-app/blob/f320b25f3677a4c893eb2ba93b6acdaeeb77857c/helm/nginx-ingress-controller-app/templates/controller-deployment.yaml#L13 but if you think using another syntax is better, it works for me :)

**Comment by webwurst** [comment]
Ok, in general I would go with best practice across the community or examples from upstream documentation. To create [least surprise](https://en.wikipedia.org/wiki/Principle_of_least_astonishment). Maybe real key-values make most sense since people are used to that for annotations anyway?

**Comment by QuentinBisson** [comment]
This now expects:
  extraAnnotations:
    key: value

**Review by webwurst — APPROVED** [review]
cool, thanks!

**Pull request merged**
