### PR TITLE
Add multiple client support

### PR DESCRIPTION
**Pull request by QuentinBisson**
@webwurst and @ced0ps Could I get your review on this ?
The idea here is to add support for multiple client IDs using the same OIDC URL.

There could be better way to achieve this but as this is something you will support, I would like your opinion on this.

Follow up PR for the config repo:

### CODE REVIEW

**Comment by QuentinBisson** [comment]
Output for multiple clients:
```yaml
---
# Source: oauth2-proxy-app/templates/network-policy.yaml
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: RELEASE-NAME
  namespace: default
  labels:
    app: "oauth2-proxy"
    app.kubernetes.io/app: "RELEASE-NAME"
    app.kubernetes.io/name: "oauth2-proxy"
    app.kubernetes.io/managed-by: "Helm"
    app.kubernetes.io/instance: "RELEASE-NAME"
    app.kubernetes.io/version: "7.1.3"
    giantswarm.io/service-type: "managed"
    helm.sh/chart: "oauth2-proxy-app-2.0.0"
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/app: "RELEASE-NAME"
      app.kubernetes.io/name: "oauth2-proxy"
  ingress:
  - ports:
    - port: 4180
      protocol: TCP
  egress:
  - {}  
  policyTypes:
  - Egress
  - Ingress
---
# Source: oauth2-proxy-app/templates/psp.yaml
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: RELEASE-NAME-psp
  namespace: default
  labels:
    app: "oauth2-proxy"
    app.kubernetes.io/app: "RELEASE-NAME"
    app.kubernetes.io/name: "oauth2-proxy"
    app.kubernetes.io/managed-by: "Helm"
    app.kubernetes.io/instance: "RELEASE-NAME"
    app.kubernetes.io/version: "7.1.3"
    giantswarm.io/service-type: "managed"
    helm.sh/chart: "oauth2-proxy-app-2.0.0"
spec:
  privileged: false
  fsGroup:
    rule: MustRunAs
    ranges:
      - min: 1
        max: 65535
  runAsUser:
    rule: MustRunAsNonRoot
  runAsGroup:
    rule: MustRunAs
    ranges:
      - min: 1
        max: 65535
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  allowPrivilegeEscalation: false
  hostNetwork: true
  hostIPC: false
  hostPID: true
---
# Source: oauth2-proxy-app/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: RELEASE-NAME
  namespace: default
---
# Source: oauth2-proxy-app/templates/secret.yaml
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: RELEASE-NAME
  namespace: default
  labels:
    app: "oauth2-proxy"
    app.kubernetes.io/app: "RELEASE-NAME"
    app.kubernetes.io/name: "oauth2-proxy"
    app.kubernetes.io/managed-by: "Helm"
    app.kubernetes.io/instance: "RELEASE-NAME"
    app.kubernetes.io/version: "7.1.3"
    giantswarm.io/service-type: "managed"
    helm.sh/chart: "oauth2-proxy-app-2.0.0"
data:
  default-client-id: ""
  default-client-secret: ""
  other-client-id: ""
  other-client-secret: ""
---
# Source: oauth2-proxy-app/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: RELEASE-NAME
  labels:
    app: "oauth2-proxy"
    app.kubernetes.io/app: "RELEASE-NAME"
    app.kubernetes.io/name: "oauth2-proxy"
    app.kubernetes.io/managed-by: "Helm"
    app.kubernetes.io/instance: "RELEASE-NAME"
    app.kubernetes.io/version: "7.1.3"
    giantswarm.io/service-type: "managed"
    helm.sh/chart: "oauth2-proxy-app-2.0.0"
rules:
  - apiGroups:
      - extensions
    resources:
      - podsecuritypolicies
    verbs:
      - use
    resourceNames:
      - RELEASE-NAME-psp
---
# Source: oauth2-proxy-app/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: RELEASE-NAME
  labels:
    app: "oauth2-proxy"
    app.kubernetes.io/app: "RELEASE-NAME"
    app.kubernetes.io/name: "oauth2-proxy"
    app.kubernetes.io/managed-by: "Helm"
    app.kubernetes.io/instance: "RELEASE-NAME"
    app.kubernetes.io/version: "7.1.3"
    giantswarm.io/service-type: "managed"
    helm.sh/chart: "oauth2-proxy-app-2.0.0"
subjects:
  - kind: ServiceAccount
    name: RELEASE-NAME
    namespace: default
roleRef:
  kind: ClusterRole
  name: RELEASE-NAME
  apiGroup: rbac.authorization.k8s.io
---
# Source: oauth2-proxy-app/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: RELEASE-NAME-default
  namespace: default
  labels:
    app: "oauth2-proxy"
    app.kubernetes.io/app: "RELEASE-NAME"
    app.kubernetes.io/name: "oauth2-proxy"
    app.kubernetes.io/managed-by: "Helm"
    app.kubernetes.io/instance: "RELEASE-NAME"
    app.kubernetes.io/version: "7.1.3"
    giantswarm.io/service-type: "managed"
    helm.sh/chart: "oauth2-proxy-app-2.0.0"
    oauth2-proxy.client: default
spec:
  ports:
  - name: http
    port: 4180
    protocol: TCP
    targetPort: 4180
  selector:
    app.kubernetes.io/app: "RELEASE-NAME"
    app.kubernetes.io/name: "oauth2-proxy"
    oauth2-proxy.client: default
apiVersion: v1
kind: Service
metadata:
  name: RELEASE-NAME-other
  namespace: default
  labels:
    app: "oauth2-proxy"
    app.kubernetes.io/app: "RELEASE-NAME"
    app.kubernetes.io/name: "oauth2-proxy"
    app.kubernetes.io/managed-by: "Helm"
    app.kubernetes.io/instance: "RELEASE-NAME"
    app.kubernetes.io/version: "7.1.3"
    giantswarm.io/service-type: "managed"
    helm.sh/chart: "oauth2-proxy-app-2.0.0"
    oauth2-proxy.client: other
spec:
  ports:
  - name: http
    port: 4180
    protocol: TCP
    targetPort: 4180
  selector:
    app.kubernetes.io/app: "RELEASE-NAME"
    app.kubernetes.io/name: "oauth2-proxy"
    oauth2-proxy.client: other
---
# Source: oauth2-proxy-app/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: RELEASE-NAME
  namespace: default
  labels:
    app: "oauth2-proxy"
    app.kubernetes.io/app: "RELEASE-NAME"
    app.kubernetes.io/name: "oauth2-proxy"
    app.kubernetes.io/managed-by: "Helm"
    app.kubernetes.io/instance: "RELEASE-NAME"
    app.kubernetes.io/version: "7.1.3"
    giantswarm.io/service-type: "managed"
    helm.sh/chart: "oauth2-proxy-app-2.0.0"
    oauth2-proxy.client: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/app: "RELEASE-NAME"
      app.kubernetes.io/name: "oauth2-proxy"
      oauth2-proxy.client: default
  template:
    metadata:
      labels:
        app: "oauth2-proxy"
        app.kubernetes.io/app: "RELEASE-NAME"
        app.kubernetes.io/name: "oauth2-proxy"
        app.kubernetes.io/managed-by: "Helm"
        app.kubernetes.io/instance: "RELEASE-NAME"
        app.kubernetes.io/version: "7.1.3"
        giantswarm.io/service-type: "managed"
        helm.sh/chart: "oauth2-proxy-app-2.0.0"
        oauth2-proxy.client: default
    spec:
      serviceAccountName: RELEASE-NAME
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      containers:
      - image: docker.io/giantswarm/oauth2-proxy:v7.1.3
        name: RELEASE-NAME
        args:
        - --cookie-expire=24h0m0s
        - --cookie-refresh=0h60m0s
        - --email-domain=*
        - --http-address=0.0.0.0:4180
        - --provider=oidc
        - --set-authorization-header=true
        - --skip-provider-button=true
        - --oidc-issuer-url=
        - --upstream=file:///dev/null
        env:
        - name: OAUTH2_PROXY_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: RELEASE-NAME
              key: default-client-id
        - name: OAUTH2_PROXY_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: RELEASE-NAME
              key: default-client-secret
        ports:
        - name: oauth2-proxy
          containerPort: 4180
          protocol: TCP
        livenessProbe:
          tcpSocket:
            port: 4180
          initialDelaySeconds: 5
          timeoutSeconds: 1
        readinessProbe:
          tcpSocket:
            port: 4180
          initialDelaySeconds: 5
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
---
# Source: oauth2-proxy-app/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: RELEASE-NAME
  namespace: default
  labels:
    app: "oauth2-proxy"
    app.kubernetes.io/app: "RELEASE-NAME"
    app.kubernetes.io/name: "oauth2-proxy"
    app.kubernetes.io/managed-by: "Helm"
    app.kubernetes.io/instance: "RELEASE-NAME"
    app.kubernetes.io/version: "7.1.3"
    giantswarm.io/service-type: "managed"
    helm.sh/chart: "oauth2-proxy-app-2.0.0"
    oauth2-proxy.client: other
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/app: "RELEASE-NAME"
      app.kubernetes.io/name: "oauth2-proxy"
      oauth2-proxy.client: other
  template:
    metadata:
      labels:
        app: "oauth2-proxy"
        app.kubernetes.io/app: "RELEASE-NAME"
        app.kubernetes.io/name: "oauth2-proxy"
        app.kubernetes.io/managed-by: "Helm"
        app.kubernetes.io/instance: "RELEASE-NAME"
        app.kubernetes.io/version: "7.1.3"
        giantswarm.io/service-type: "managed"
        helm.sh/chart: "oauth2-proxy-app-2.0.0"
        oauth2-proxy.client: other
    spec:
      serviceAccountName: RELEASE-NAME
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      containers:
      - image: docker.io/giantswarm/oauth2-proxy:v7.1.3
        name: RELEASE-NAME
        args:
        - --cookie-expire=24h0m0s
        - --cookie-refresh=0h60m0s
        - --email-domain=*
        - --http-address=0.0.0.0:4180
        - --provider=oidc
        - --set-authorization-header=true
        - --skip-provider-button=true
        - --oidc-issuer-url=
        - --upstream=file:///dev/null
        env:
        - name: OAUTH2_PROXY_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: RELEASE-NAME
              key: other-client-id
        - name: OAUTH2_PROXY_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: RELEASE-NAME
              key: other-client-secret
        ports:
        - name: oauth2-proxy
          containerPort: 4180
          protocol: TCP
        livenessProbe:
          tcpSocket:
            port: 4180
          initialDelaySeconds: 5
          timeoutSeconds: 1
        readinessProbe:
          tcpSocket:
            port: 4180
          initialDelaySeconds: 5
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
```

**Comment by QuentinBisson** [comment]
Output with single client:

```yaml
# Source: oauth2-proxy-app/templates/network-policy.yaml
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: RELEASE-NAME
  namespace: default
  labels:
    app: "oauth2-proxy"
    app.kubernetes.io/app: "RELEASE-NAME"
    app.kubernetes.io/name: "oauth2-proxy"
    app.kubernetes.io/managed-by: "Helm"
    app.kubernetes.io/instance: "RELEASE-NAME"
    app.kubernetes.io/version: "7.1.3"
    giantswarm.io/service-type: "managed"
    helm.sh/chart: "oauth2-proxy-app-2.0.0"
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/app: "RELEASE-NAME"
      app.kubernetes.io/name: "oauth2-proxy"
  ingress:
  - ports:
    - port: 4180
      protocol: TCP
  egress:
  - {}  
  policyTypes:
  - Egress
  - Ingress
---
# Source: oauth2-proxy-app/templates/psp.yaml
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: RELEASE-NAME-psp
  namespace: default
  labels:
    app: "oauth2-proxy"
    app.kubernetes.io/app: "RELEASE-NAME"
    app.kubernetes.io/name: "oauth2-proxy"
    app.kubernetes.io/managed-by: "Helm"
    app.kubernetes.io/instance: "RELEASE-NAME"
    app.kubernetes.io/version: "7.1.3"
    giantswarm.io/service-type: "managed"
    helm.sh/chart: "oauth2-proxy-app-2.0.0"
spec:
  privileged: false
  fsGroup:
    rule: MustRunAs
    ranges:
      - min: 1
        max: 65535
  runAsUser:
    rule: MustRunAsNonRoot
  runAsGroup:
    rule: MustRunAs
    ranges:
      - min: 1
        max: 65535
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  allowPrivilegeEscalation: false
  hostNetwork: true
  hostIPC: false
  hostPID: true
---
# Source: oauth2-proxy-app/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: RELEASE-NAME
  namespace: default
---
# Source: oauth2-proxy-app/templates/secret.yaml
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: RELEASE-NAME
  namespace: default
  labels:
    app: "oauth2-proxy"
    app.kubernetes.io/app: "RELEASE-NAME"
    app.kubernetes.io/name: "oauth2-proxy"
    app.kubernetes.io/managed-by: "Helm"
    app.kubernetes.io/instance: "RELEASE-NAME"
    app.kubernetes.io/version: "7.1.3"
    giantswarm.io/service-type: "managed"
    helm.sh/chart: "oauth2-proxy-app-2.0.0"
data:
  client-id: ""
  client-secret: ""
---
# Source: oauth2-proxy-app/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: RELEASE-NAME
  labels:
    app: "oauth2-proxy"
    app.kubernetes.io/app: "RELEASE-NAME"
    app.kubernetes.io/name: "oauth2-proxy"
    app.kubernetes.io/managed-by: "Helm"
    app.kubernetes.io/instance: "RELEASE-NAME"
    app.kubernetes.io/version: "7.1.3"
    giantswarm.io/service-type: "managed"
    helm.sh/chart: "oauth2-proxy-app-2.0.0"
rules:
  - apiGroups:
      - extensions
    resources:
      - podsecuritypolicies
    verbs:
      - use
    resourceNames:
      - RELEASE-NAME-psp
---
# Source: oauth2-proxy-app/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: RELEASE-NAME
  labels:
    app: "oauth2-proxy"
    app.kubernetes.io/app: "RELEASE-NAME"
    app.kubernetes.io/name: "oauth2-proxy"
    app.kubernetes.io/managed-by: "Helm"
    app.kubernetes.io/instance: "RELEASE-NAME"
    app.kubernetes.io/version: "7.1.3"
    giantswarm.io/service-type: "managed"
    helm.sh/chart: "oauth2-proxy-app-2.0.0"
subjects:
  - kind: ServiceAccount
    name: RELEASE-NAME
    namespace: default
roleRef:
  kind: ClusterRole
  name: RELEASE-NAME
  apiGroup: rbac.authorization.k8s.io
---
# Source: oauth2-proxy-app/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: RELEASE-NAME
  namespace: default
  labels:
    app: "oauth2-proxy"
    app.kubernetes.io/app: "RELEASE-NAME"
    app.kubernetes.io/name: "oauth2-proxy"
    app.kubernetes.io/managed-by: "Helm"
    app.kubernetes.io/instance: "RELEASE-NAME"
    app.kubernetes.io/version: "7.1.3"
    giantswarm.io/service-type: "managed"
    helm.sh/chart: "oauth2-proxy-app-2.0.0"
spec:
  ports:
  - name: http
    port: 4180
    protocol: TCP
    targetPort: 4180
  selector:
    app.kubernetes.io/app: "RELEASE-NAME"
    app.kubernetes.io/name: "oauth2-proxy"
---
# Source: oauth2-proxy-app/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: RELEASE-NAME
  namespace: default
  labels:
    app: "oauth2-proxy"
    app.kubernetes.io/app: "RELEASE-NAME"
    app.kubernetes.io/name: "oauth2-proxy"
    app.kubernetes.io/managed-by: "Helm"
    app.kubernetes.io/instance: "RELEASE-NAME"
    app.kubernetes.io/version: "7.1.3"
    giantswarm.io/service-type: "managed"
    helm.sh/chart: "oauth2-proxy-app-2.0.0"
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/app: "RELEASE-NAME"
      app.kubernetes.io/name: "oauth2-proxy"
  template:
    metadata:
      labels:
        app: "oauth2-proxy"
        app.kubernetes.io/app: "RELEASE-NAME"
        app.kubernetes.io/name: "oauth2-proxy"
        app.kubernetes.io/managed-by: "Helm"
        app.kubernetes.io/instance: "RELEASE-NAME"
        app.kubernetes.io/version: "7.1.3"
        giantswarm.io/service-type: "managed"
        helm.sh/chart: "oauth2-proxy-app-2.0.0"
    spec:
      serviceAccountName: RELEASE-NAME
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      containers:
      - image: docker.io/giantswarm/oauth2-proxy:v7.1.3
        name: RELEASE-NAME
        args:
        - --cookie-expire=24h0m0s
        - --cookie-refresh=0h60m0s
        - --email-domain=*
        - --http-address=0.0.0.0:4180
        - --provider=oidc
        - --set-authorization-header=true
        - --skip-provider-button=true
        - --oidc-issuer-url=
        - --upstream=file:///dev/null
        env:
        - name: OAUTH2_PROXY_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: RELEASE-NAME
              key: client-id
        - name: OAUTH2_PROXY_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: RELEASE-NAME
              key: client-secret
        ports:
        - name: oauth2-proxy
          containerPort: 4180
          protocol: TCP
        livenessProbe:
          tcpSocket:
            port: 4180
          initialDelaySeconds: 5
          timeoutSeconds: 1
        readinessProbe:
          tcpSocket:
            port: 4180
          initialDelaySeconds: 5
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
```

**Review by webwurst — APPROVED** [review]
Is this based on some upstream charts? Should we use https://github.com/oauth2-proxy/oauth2-proxy instead? I can't really judge on this PR unless I take some dedicated time. If this makes sense and works for you and in all the places we use it currently use it, feel free to merge.

**Comment by QuentinBisson** [comment]
Thanks. We built this chart a long time ago for the management cluster and I'm changing it a bit to allow customers to install it. The image used is  https://github.com/oauth2-proxy/oauth2-proxy but I'm retagging it using retagger (https://quay.io/repository/giantswarm/oauth2-proxy?tab=tags).

I basically added support for multiple client as the customer in need of this app uses multiple client IDs in the same cluster

**Comment by webwurst** [comment]
Ok, just realized from the version number we are using the official upstream binary. Please update our readme then :)
> It is build upon the bitly/oauth2_proxy, with the configuration:

**Pull request merged**
