### PR TITLE
Major refactoring to be able to properly support multiple oauth-provider

### PR DESCRIPTION
**Pull request by QuentinBisson**
This PR does a major refactoring of the oauth2-proxy. THis will be split into a few smaller PRs for things that can be

### CODE REVIEW

**Review by TheoBrigitte — APPROVED** [review]

**Comment by QuentinBisson** [comment]
@TheoBrigitte did you review this entirely? Damn

**Comment by TheoBrigitte** [comment]
I did my best there are a lot of redundand things being moved around so I skimmed through them, I also did not review the values schema for instance

**Comment by QuentinBisson** [comment]
This PR:
- remove single provider configurations on CAPI as we know we will need at least a giantswarm and customer provider so this removes all cases where oauth2-proxy is mono provider so no more `if eq 1 (len $.Values.oauth2Proxy.providers)`. This also moves all properties like client-id, cookie-name, pass-access-token under the provider config.
- removes deprecated host property
- removes the "existingSecret" field as this is not intended for customer use so let's always create it
- align ingress class name with other charts
- align pod and container security contexts with other charts
- removes push to aws collection to make sure this does not impact vintage installations

**Comment by QuentinBisson** [comment]
I updated the changelog

**Pull request merged**
